### ISSUE TITLE
Why am I getting write errors on a particular ssd?

### ISSUE THREAD

**Issue by ksm9413** [developer-onizuka/gpudirect_storage_1.0_VirtualMachine#1]
Hello developer-onizuka,

I Have one question 
What exactly is causing the error on a specific ssd when performing a write operation using GPUDirect Storage?

-----------------------------------------
root@syseng-desktop:/usr/local/cuda-11.4/gds/tools# ./gdsio -f /mnt/test10G -d 0 -n 0 -w 1 -s 10G -x 0 -I 1 -T 10 -i 4096K
Error: IO failed stopping traffic, fd :27 ret:-5 errno :1
io failed :ret :-5 errno :1, file offset :0, block size :4194304
-----------------------------------------
[ 690.004369] EXT4-fs (nvme0n1): recovery complete
[ 690.004896] EXT4-fs (nvme0n1): mounted filesystem with ordered data mode. Opts: data=ordered
[ 748.642116] nvme nvme0: controller is down; will reset: CSTS=0x3, PCI_STATUS=0x2010
[ 748.705906] nvme nvme0: Shutdown timeout set to 8 seconds
[ 748.758419] nvme nvme0: 12/0/0 default/read/poll queues
[ 779.362181] nvme nvme0: I/O 1004 QID 1 timeout, disable controller
[ 779.394769] blk_update_request: I/O error, dev nvme0n1, sector 22699520 op 0x1:(WRITE) flags 0x8800 phys_seg 1 prio class 0
[ 779.394781] blk_update_request: I/O error, dev nvme0n1, sector 22696960 op 0x1:(WRITE) flags 0xc800 phys_seg 2 prio class 0
[ 779.394788] blk_update_request: I/O error, dev nvme0n1, sector 22694400 op 0x1:(WRITE) flags 0xc800 phys_seg 1 prio class 0
[ 779.394793] blk_update_request: I/O error, dev nvme0n1, sector 22691840 op 0x1:(WRITE) flags 0xc800 phys_seg 4 prio class 0
[ 779.394851] nvme nvme0: failed to mark controller live state
[ 779.394855] nvme nvme0: Removing after probe failure status: -19
[ 779.394873] nvidia-fs:write IO failed :-5
[ 779.418191] blk_update_request: I/O error, dev nvme0n1, sector 486801416 op 0x1:(WRITE) flags 0x800 phys_seg 8 prio class 0
[ 779.418226] Aborting journal on device nvme0n1-8.
[ 779.418242] Buffer I/O error on dev nvme0n1, logical block 60850176, lost sync page write
[ 779.418248] JBD2: Error -5 detected when updating journal superblock for nvme0n1-8.
[ 779.447856] nvme nvme0: failed to set APST feature (-19)

**Comment by developer-onizuka** [comment]
Hi,
This is what I am investigating about. But I don't have any solution in this moment besides using the following NVMe SSDs.
- KLEVV SSD 256GB CRAS C710 M.2 Type2280 PCIe3x4 NVMe 3D TLC NAND Flash (P/N: K256GM2SP0-C71)
- KLEVV SSD 512GB CRAS C710 M.2 Type2280 PCIe3x4 NVMe 3D TLC NAND Flash (P/N: K512GM2SP0-C71)

The point is both NVMe devices are using Silicon Motion controller.

The following devices are failed about GDS. These NVMes are using other controllers rather than Silicon Motion.
I am gonna check differences from the perspectives of the PCI configuration such as MayPayload and MaxReadRequest etc.

-  SK hynix BC501 NVMe Solid State Drive 128GB
    P/N: HFM128GDJTNG-8310A
    Performance Spec: Read 1400MB/s, Write 395MB/s

-  Phison Electronics Corporation E12 NVMe Controller 512GB
    P/N: PS5012-E12S-512G
    Performance Spec: Read 3400MB/s、Write 2400MB/s

-   SM961 Series MZ-VLW1280 128GB M.2 Type2280 PCIe3x4 NVMe 
    P/N: MZVLW128HEGR-000L1
    Performance Spec: Read 2800MB/s, Write 600MB/s

**Comment by ksm9413** [comment]
I will ask more questions
What if I want to use GDS in a docker container environment?

**Comment by developer-onizuka** [comment]
Hi, 
You can use GDS even in a container environment through this topic.
